# Generated by Django 4.1.7 on 2023-03-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230315_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
