# Generated by Django 4.1.7 on 2023-03-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrateur'), ('SUBSCRIBER', 'Utilisateur')], default='SUBSCRIBER', max_length=30, verbose_name='Rôle'),
        ),
    ]
